// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;

namespace Demo2_CapitalMarketStory
{
    public partial class MLCapitalModel
    {
        public const string RetrainFilePath =  @"C:\Users\Solomon\Documents\Materiale facultate anul 3 sem 2\LICENTA\dataGovRo\dateFin10ani.csv";
        public const char RetrainSeparatorChar = ';';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"I1", @"I1"),new InputOutputColumnPair(@"I2", @"I2"),new InputOutputColumnPair(@"I3", @"I3"),new InputOutputColumnPair(@"I4", @"I4"),new InputOutputColumnPair(@"I5", @"I5"),new InputOutputColumnPair(@"I6", @"I6"),new InputOutputColumnPair(@"I7", @"I7"),new InputOutputColumnPair(@"I8", @"I8"),new InputOutputColumnPair(@"I9", @"I9"),new InputOutputColumnPair(@"I11", @"I11"),new InputOutputColumnPair(@"I12", @"I12"),new InputOutputColumnPair(@"I13", @"I13"),new InputOutputColumnPair(@"I14", @"I14"),new InputOutputColumnPair(@"I15", @"I15"),new InputOutputColumnPair(@"I16", @"I16"),new InputOutputColumnPair(@"I17", @"I17"),new InputOutputColumnPair(@"I18", @"I18"),new InputOutputColumnPair(@"I19", @"I19"),new InputOutputColumnPair(@"I20", @"I20"),new InputOutputColumnPair(@"An", @"An")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"I1",@"I2",@"I3",@"I4",@"I5",@"I6",@"I7",@"I8",@"I9",@"I11",@"I12",@"I13",@"I14",@"I15",@"I16",@"I17",@"I18",@"I19",@"I20",@"An"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=1575,NumberOfIterations=2449,MinimumExampleCountPerLeaf=24,LearningRate=0.5063241930397822,LabelColumnName=@"I10",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.1112883085837593,FeatureFraction=0.99999999,L1Regularization=6.514868248958277E-10,L2Regularization=0.9999997766729865},MaximumBinCountPerFeature=269}));

            return pipeline;
        }
    }
 }
