// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

namespace Demo2_CapitalMarketStory
{
    public partial class MLProfitNetModel
    {
        /// <summary>
        /// model input class for MLProfitNetModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(19)]
            [ColumnName(@"Profitul Net")]
            public float Profitul_Net { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLProfitNetModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Profitul Net")]
            public float[] Profitul_Net { get; set; }

            [ColumnName(@"Profitul Net_LB")]
            public float[] Profitul_Net_LB { get; set; }

            [ColumnName(@"Profitul Net_UB")]
            public float[] Profitul_Net_UB { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"C:\Users\Solomon\Documents\Materiale facultate anul 3 sem 2\LICENTA\Demo2_CapitalMarketStory\MLProfitNetModel.mlnet");

        public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input, horizon);
        }

        private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }
    }
}

