// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Demo2_CapitalMarketStory
{
    public partial class MLTESTModel
    {
        /// <summary>
        /// model input class for MLTESTModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(2)]
            [ColumnName(@"I1")]
            public float I1 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"I2")]
            public float I2 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"I7")]
            public float I7 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"I10")]
            public float I10 { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"I13")]
            public float I13 { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"I18")]
            public float I18 { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"I20")]
            public float I20 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLTESTModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"I1")]
            public float I1 { get; set; }

            [ColumnName(@"I2")]
            public float I2 { get; set; }

            [ColumnName(@"I7")]
            public float I7 { get; set; }

            [ColumnName(@"I10")]
            public float I10 { get; set; }

            [ColumnName(@"I13")]
            public float I13 { get; set; }

            [ColumnName(@"I18")]
            public float I18 { get; set; }

            [ColumnName(@"I20")]
            public float I20 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLTESTModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
