// <auto-generated />
using System;
using Demo2_CapitalMarketStory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo2_CapitalMarketStory.Migrations
{
    [DbContext(typeof(Demo2_CapitalMarketStoryContext))]
    [Migration("20260304131018_ChangedDateRange")]
    partial class ChangedDateRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<int>("CAEN")
                        .HasColumnType("int");

                    b.Property<int>("CUI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadquartersAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Website")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Import", b =>
                {
                    b.Property<int>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ImportId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Import");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.YearlyFinancialReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<double>("ActiveCirculante")
                        .HasColumnType("float");

                    b.Property<double>("ActiveImobilizate")
                        .HasColumnType("float");

                    b.Property<int>("CUI")
                        .HasColumnType("int");

                    b.Property<double>("CapitaluriTotale")
                        .HasColumnType("float");

                    b.Property<double>("CapitaluriVarsate")
                        .HasColumnType("float");

                    b.Property<double>("Casa")
                        .HasColumnType("float");

                    b.Property<double>("CheltuieliAvans")
                        .HasColumnType("float");

                    b.Property<double>("CheltuieliTotale")
                        .HasColumnType("float");

                    b.Property<double>("CifraAfaceriNet")
                        .HasColumnType("float");

                    b.Property<double>("Creante")
                        .HasColumnType("float");

                    b.Property<double>("Datorii")
                        .HasColumnType("float");

                    b.Property<int>("ImportId")
                        .HasColumnType("int");

                    b.Property<decimal>("MarjaProfit")
                        .HasColumnType("decimal(14,4)");

                    b.Property<int>("NumarSalariati")
                        .HasColumnType("int");

                    b.Property<double>("Patrimoniu")
                        .HasColumnType("float");

                    b.Property<double>("PierdereBrut")
                        .HasColumnType("float");

                    b.Property<double>("PierdereNet")
                        .HasColumnType("float");

                    b.Property<double>("ProfitBrut")
                        .HasColumnType("float");

                    b.Property<double>("ProfitNet")
                        .HasColumnType("float");

                    b.Property<double>("Provizioane")
                        .HasColumnType("float");

                    b.Property<decimal>("ROA")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("ROE")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("RataCrestereCifraAfaceriNet")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("RataCrestereProfitNet")
                        .HasColumnType("decimal(14,4)");

                    b.Property<double>("Stocuri")
                        .HasColumnType("float");

                    b.Property<double>("VenituriAvans")
                        .HasColumnType("float");

                    b.Property<double>("VenituriTotale")
                        .HasColumnType("float");

                    b.Property<int>("YearReported")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("ImportId");

                    b.ToTable("YearlyFinancialReport");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Import", b =>
                {
                    b.HasOne("Demo2_CapitalMarketStory.Models.Company", "Company")
                        .WithMany("Imports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.YearlyFinancialReport", b =>
                {
                    b.HasOne("Demo2_CapitalMarketStory.Models.Import", "Import")
                        .WithMany("Reports")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Company", b =>
                {
                    b.Navigation("Imports");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Import", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
