// <auto-generated />
using System;
using Demo2_CapitalMarketStory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo2_CapitalMarketStory.Migrations
{
    [DbContext(typeof(Demo2_CapitalMarketStoryContext))]
    partial class Demo2_CapitalMarketStoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<int>("CAEN")
                        .HasColumnType("int");

                    b.Property<int>("CUI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadquartersAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Import", b =>
                {
                    b.Property<int>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("ImportId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Import");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.YearlyFinancialReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<decimal>("ActiveCirculante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActiveImobilizate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CUI")
                        .HasColumnType("int");

                    b.Property<decimal>("CapitaluriTotale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapitaluriVarsate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Casa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CheltuieliAvans")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CheltuieliTotale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CifraAfaceriNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Creante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Datorii")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImportId")
                        .HasColumnType("int");

                    b.Property<decimal>("MarjaProfit")
                        .HasColumnType("decimal(14,4)");

                    b.Property<int?>("NumarSalariati")
                        .HasColumnType("int");

                    b.Property<decimal>("Patrimoniu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PierdereBrut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PierdereNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitBrut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Provizioane")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ROA")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("ROE")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("RataCrestereCifraAfaceriNet")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("RataCrestereProfitNet")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("Stocuri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VenituriAvans")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VenituriTotale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearReported")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("ImportId");

                    b.ToTable("YearlyFinancialReport");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Import", b =>
                {
                    b.HasOne("Demo2_CapitalMarketStory.Models.Company", "Company")
                        .WithMany("Imports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.YearlyFinancialReport", b =>
                {
                    b.HasOne("Demo2_CapitalMarketStory.Models.Import", "Import")
                        .WithMany("Reports")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Company", b =>
                {
                    b.Navigation("Imports");
                });

            modelBuilder.Entity("Demo2_CapitalMarketStory.Models.Import", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
